// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxU1ge084NxuhQQKwyBIcvEZadQ1lTUiM',
    appId: '1:74448743975:web:cc833965fced3a90842802',
    messagingSenderId: '74448743975',
    projectId: 'fir-test-8a8cd',
    authDomain: 'fir-test-8a8cd.firebaseapp.com',
    storageBucket: 'fir-test-8a8cd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0nRV6qaRqpgtynCGVHSEjCtG3xD1l9XM',
    appId: '1:74448743975:android:8d0cf0b872056bfe842802',
    messagingSenderId: '74448743975',
    projectId: 'fir-test-8a8cd',
    storageBucket: 'fir-test-8a8cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAUyQn6U9IZHaboJe2vQ2vnivUZvfu_Jo',
    appId: '1:74448743975:ios:2f60c772b295cdff842802',
    messagingSenderId: '74448743975',
    projectId: 'fir-test-8a8cd',
    storageBucket: 'fir-test-8a8cd.appspot.com',
    androidClientId: '74448743975-dasf4p5k8qvalstd8qro1pq0gdedu6np.apps.googleusercontent.com',
    iosClientId: '74448743975-p21l2tfroh09gvn10hbsogrn4l4jdhdm.apps.googleusercontent.com',
    iosBundleId: 'com.example.signapp',
  );
}
